"""十类生活情境的固定分组。Schema、工具说明和前端目录共同使用此定义。"""

MODULE_FIELDS = {
    "employment": {
        "organization": "name sector industry",
        "role": "title work_content responsibilities",
        "working_arrangement": "employment_form workplace schedule flexibility",
        "experience": "workload autonomy satisfaction_and_frustrations",
        "outlook": "current_priorities intended_changes",
    },
    "education": {
        "institution": "name education_form",
        "study": "stage field courses_and_tasks exams_and_deadlines",
        "arrangement": "location schedule learning_style",
        "experience": "interests pressure_and_difficulties peer_environment",
        "outlook": "next_steps",
    },
    "job_search": {
        "current_state": "employment_background search_stage",
        "direction": "target_roles sector_preferences location_preferences",
        "progress": "applications interviews offers_and_decisions",
        "conditions": "constraints concerns",
        "outlook": "next_actions alternatives",
    },
    "entrepreneurship": {
        "venture": "name business_or_product stage",
        "participation": "own_role team_and_partners",
        "operation": "daily_work time_commitment",
        "conditions": "resources difficulties",
        "outlook": "near_term_goals",
    },
    "care_work": {
        "recipient": "relationship care_needs",
        "responsibilities": "tasks time_commitment",
        "coordination": "division_of_work support_network",
        "experience": "life_impact feelings",
        "outlook": "expected_changes",
    },
    "retirement": {
        "transition": "previous_engagement retirement_arrangement",
        "daily_life": "main_activities time_structure social_connections",
        "conditions": "resources_and_constraints",
        "outlook": "plans_and_interests",
    },
    "rest": {
        "background": "reason_or_context voluntary_or_constrained",
        "daily_life": "activities time_structure social_connections",
        "experience": "recovery_and_feelings",
        "outlook": "return_or_next_steps",
    },
    "migration": {
        "move": "from_place to_place reason_or_context",
        "arrangement": "housing logistics timing",
        "progress": "completed_and_pending",
        "experience": "adaptation life_impact",
    },
    "household_transition": {
        "change": "before after participants",
        "arrangement": "housing responsibility_changes",
        "progress": "completed_and_pending",
        "experience": "feelings unresolved_matters",
    },
    "other": {
        "topic": "name scope",
        "situation": "current_activity people_and_environment",
        "conditions": "resources_and_constraints",
        "experience": "feelings",
        "outlook": "next_steps",
    },
}

MODULE_LABELS = dict(
    zip(
        MODULE_FIELDS,
        (
            "工作",
            "学习",
            "求职",
            "创业",
            "照料",
            "退休",
            "休整",
            "迁移",
            "家庭变化",
            "其他情境",
        ),
        strict=True,
    )
)

# 字段语义与结构在同一目录维护，生成 Schema 时直接使用，不在 Prompt 重复一套表单。
MODULE_FIELD_MEANINGS = {
    "name": "机构、项目或情境的实际名称；未知不要编造",
    "sector": "组织性质与制度环境，如国企、外企，不是人格分类",
    "industry": "所属行业与业务领域",
    "title": "具体职位或角色名称",
    "work_content": "平时具体处理什么工作",
    "responsibilities": "本人承担哪些职责与责任边界",
    "employment_form": "雇佣、实习、兼职等劳动参与方式",
    "workplace": "工作地点与现场、远程等场所安排",
    "schedule": "实际时间安排，区分本人和他人、通常规律和单次事件，不编造精确时间",
    "flexibility": "时间与地点可以怎样调整，有何现实限制",
    "workload": "实际任务量与工作压力，不据此直接判断人格",
    "autonomy": "该情境中可自主决定什么，哪些由制度或他人决定",
    "satisfaction_and_frustrations": "本人对工作的满意、挫折与具体原因",
    "current_priorities": "此阶段优先推进的工作事项",
    "intended_changes": "本人希望或计划改变的工作状态，区分想法与确认",
    "education_form": "全日制、在职等学习形式",
    "stage": "当前所处阶段，保留时期边界",
    "field": "专业、方向或所学领域",
    "courses_and_tasks": "具体课程、学习任务与项目",
    "exams_and_deadlines": "考试和明确期限；不知道日期时保留模糊时间",
    "location": "该活动的地点环境，不编造精确地址",
    "learning_style": "实际采用的学习与组织方式，不贴学习类型标签",
    "interests": "本人在学习中感兴趣的内容",
    "pressure_and_difficulties": "具体学习压力与困难",
    "peer_environment": "同学、同伴与学习环境的影响",
    "next_steps": "本人接下来准备做什么，区分意向与承诺",
    "employment_background": "求职前的就业背景与当前状态",
    "search_stage": "目前求职进展阶段",
    "target_roles": "希望寻找的岗位方向",
    "sector_preferences": "对行业和组织性质的偏好及理由",
    "location_preferences": "对工作城市或地点的偏好及限制",
    "applications": "已投递或计划投递的进展",
    "interviews": "面试安排、过程与结果，区分预计和已发生",
    "offers_and_decisions": "实际机会、录用与本人取舍",
    "constraints": "影响行动的现实限制",
    "concerns": "对此情境的顾虑及在意之处",
    "next_actions": "接下来拟采取的具体行动",
    "alternatives": "仍在考虑的其他可选方向",
    "business_or_product": "创业业务或产品在做什么",
    "own_role": "本人在项目中承担的角色",
    "team_and_partners": "参与团队与合作关系",
    "daily_work": "日常具体投入的工作",
    "time_commitment": "实际投入的时间与节奏，不把某天时长升级为固定规律",
    "resources": "目前可使用的资源与支持，不编造收入资产",
    "difficulties": "推进过程中具体困难",
    "near_term_goals": "近期目标和预期进展",
    "relationship": "照料对象与本人的关系，区分发送者和事实主体",
    "care_needs": "照料对象需要何种日常帮助，不擅自诊断",
    "tasks": "本人具体承担的照料任务",
    "division_of_work": "照料责任如何在不同人之间分配",
    "support_network": "可提供支持的人与组织",
    "life_impact": "此情境怎样影响日常生活、时间和其他事务",
    "feelings": "本人对这个具体情境的感受与理解",
    "expected_changes": "预期将发生的变化，不当作已发生事实",
    "previous_engagement": "退休前主要从事的工作或事务",
    "retirement_arrangement": "退休方式及阶段安排",
    "main_activities": "当前日常主要活动",
    "time_structure": "一天或一周的时间组织方式",
    "social_connections": "在此情境中维持的社会联系",
    "resources_and_constraints": "可用资源和实际限制，不编造精确财务或健康事实",
    "plans_and_interests": "当前计划与感兴趣的方向",
    "reason_or_context": "进入此状态或作此选择的原因和背景，保留不确定性",
    "voluntary_or_constrained": "休整是主动选择还是受现实条件约束，允许混合或不明",
    "activities": "休整期间实际在做什么",
    "recovery_and_feelings": "休整体验、恢复感受与变化，不作临床评估",
    "return_or_next_steps": "何时或怎样回到其他事务，以及下一步方向",
    "from_place": "迁出地；只记录材料支持的地点粒度",
    "to_place": "迁入地；区分计划与已抵达",
    "housing": "居住安排和条件，不编造地址或房产归属",
    "logistics": "搬迁交通、物品与手续安排",
    "timing": "相关时间与期限，允许模糊描述",
    "completed_and_pending": "哪些已完成、哪些仍待办，不能混写",
    "adaptation": "对新环境的适应与具体困难",
    "before": "家庭变化之前的状态",
    "after": "变化之后或拟变化后的状态，明确是否已经发生",
    "participants": "此家庭变化涉及的人及关系",
    "responsibility_changes": "变化导致的家庭责任调整",
    "unresolved_matters": "仍未解决的具体事项",
    "scope": "此其他情境的边界，不与其他模块重复堆叠",
    "current_activity": "该情境中正在进行的具体活动",
    "people_and_environment": "参与的人以及相关现实环境",
}
