"""跨 Agent 协作事务的总预算；单个 Agent 策略统一在 agent_runtime.policy。"""

# 协作预算不会因角色切换重置；不是固定工作轮数或成功标准。
COLLABORATION_MAX_HANDOFFS = 64
COLLABORATION_TIMEOUT_SECONDS = 3600.0
COLLABORATION_MAX_MODEL_STEPS = 256
COLLABORATION_MAX_TOOL_CALLS = 256
COLLABORATION_MAX_PROVIDER_TOKENS = 2_000_000
